### PR TITLE
Add nodeLimit and maxLineCount as options

### PR DESCRIPTION
**Pull request by evonck**
Add nodeLimit and maxLineCount as options.
This will allow us to tweak the size on the BE without need of a deploy of talon

### CODE REVIEW

**Comment by evonck** [comment]
@quentez if you have time to check this one. Thx

**Comment by quentez** [comment]
@evonck Will check this afternoon.

**Review by quentez — APPROVED** [review]

**Comment by quentez** [comment]
@evonck Updated the format of options to be consistent.
Let me know if it's good and I'll publish the version.

**Comment by evonck** [comment]
LGTM. If you can also check the other one it would be great. Thx

**Comment by quentez** [comment]
@evonck Yes. Will check the other one soon.

**Pull request merged**
